First implementation of Mod Settings UI
EmulatorNexus/Fusion-UI pull request #22
Opened 2022-08-10 22:24 UTC by paulhobbel

The first Mod Settings UI implementation

General settings:
![image](https://user-images.githubusercontent.com/20015650/184030950-d10d800f-fbed-4964-aba4-66a0faa7514d.png)

Mod settings:
![image](https://user-images.githubusercontent.com/20015650/184030918-1ed865a9-8323-4f19-ab40-5eb9965011df.png)

2022-08-12 11:29 UTC, OrfeasZ requested changes

2022-08-12 11:29 UTC, OrfeasZ commented on app/components/inputs/OptionsInput.js
> +                isClearable={this.props.allowEmpty??false}
This can probably be simplified as `!!this.props.allowEmpty`.

2022-08-12 11:29 UTC, OrfeasZ commented on app/containers/Settings.js
> +        let audioSettings = (
Might be a good idea to move these into their own components (audio, game, mods).

2022-08-12 11:29 UTC, OrfeasZ commented on app/containers/Settings.js
> +                    return  <>Unsupported</>; // TODO: Fixme
This should be implemented prior to merging.

2022-08-12 11:29 UTC, OrfeasZ commented on assets/scss/_settings.scss
> +    backdrop-filter: blur(10px);
Pixel value should probably be vh.

2022-08-12 11:29 UTC, OrfeasZ commented on app/constants/Styles.js
> +        backdropFilter: 'blur(20px)',
Px value should probably be in vh.

2022-08-16 08:30 UTC, paulhobbel commented on app/components/settings/AudioSettings.js
> +class AudioSettings extends Component
This is a container or smart component so it should be in the containers folder. Or you have to make it a dumb component and pass changes by events

2022-09-09 13:16 UTC, OrfeasZ approved these changes

2022-09-09 13:16 UTC, merged